### ISSUE TITLE
Occasional 401 on /api

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1299]
### Describe the Bug
Occasionally, there will be an error doing something, such as going to profile or subscriptions.  Checking the browser console shows that when this happens there is always a 401 for the `/api` path relating to where I was trying to go.  This was happening frequently on `:0.9`, switching to `:dev` reduced it drastically but it still happens.

### Steps to Reproduce the Bug

It's not predictably reproducible. I've noticed it clicking on profile or subscriptions, but that's all I've done with viewtube so far.

### Expected Behaviour

The page loads without errors.

### Device Info 

- Device: desktop
- OS: I use Arch btw ;-)
- Browser: Firefox and Vivaldi
- Version: latest

### Additional Context

Might be related to #1114?

`docker-compose.yml`
```yaml
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:dev
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - VIEWTUBE_URL=http://localhost:8066
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_DATA_DIRECTORY=/data
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

networks:
  viewtube:
```
