### ISSUE TITLE
Video progress bar not shown on thumbnail in subscription view

### ISSUE THREAD

**Issue by sdfg2** [mauriceoegerli/viewtube-vue#1302]
### Describe the Bug

Video progress bar not shown on thumbnail in subscription view

### Steps to Reproduce the Bug

1. Go to profile, see video has progress bar
2. Go to subscriptions, see same video has no progress bar

### Expected Behaviour

The progress bar should display correctly in the subscriptions feed.

### Screenshot/Screen recording

Profile view:
![image](https://user-images.githubusercontent.com/5736478/158568825-b55cff61-1198-4a9d-a99b-d0295cbb9a3b.png)
Subscription view:
![image](https://user-images.githubusercontent.com/5736478/158568980-d9256e5e-1f77-42e1-9007-c78c60d22233.png)

### Device Info 

- Device: desktop
- OS: Arch
- Browser: vivaldi 5.1.2567.57-1

### Additional Context

`docker-compose.yml`
```yaml
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:dev
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - VIEWTUBE_URL=http://localhost:8066
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_DATA_DIRECTORY=/data
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

networks:
  viewtube:
```

Checking the source, there is an element already there for it:
`<div class="video-saved-progress" style="width: 0%;"></div>`
Adjusting the `width` makes the progress bar change, so I'm guessing it's just something in the backend not telling it what width it should be.
