### ISSUE TITLE
Docker dev-arm64 image exec format error

### ISSUE THREAD

**Issue by ghost** [mauriceoegerli/viewtube-vue#1318]
Viewtube latest, dev-arm64 & 0.9.* won`t work because of exec format error. VM used for deployment is Oracle Cloud A1 Compute.
```
Linux rocky-arm64 5.10.0-12-arm64 #1 SMP Debian 5.10.103-1 (2022-03-07) aarch64 GNU/Linux
```
```
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                          PORTS       NAMES
f71963903191   mauriceo/viewtube:dev-linux-arm64   "node -r /home/app/.…"   5 minutes ago   Restarting (1) 14 seconds ago               viewtube
70e4b4f50beb   arm64v8/mongo:4.4                   "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes                    27017/tcp   viewtube-mongodb
8178672aaabe   arm64v8/redis:6                     "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes                    6379/tcp    viewtube-redis
```
```
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:dev-linux-arm64
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - VIEWTUBE_URL=X
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_DATA_DIRECTORY=/data
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: arm64v8/mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: arm64v8/redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

networks:
  viewtube:
```
