### ISSUE TITLE
The new docker images don't seem to be working on arm64

### ISSUE THREAD

**Issue by moisout** [mauriceoegerli/viewtube-vue#1321]
The new docker images don't seem to be working on arm64 - they yield the same error as if I used the amd64 image on a Raspberry Pi 4B: `viewtube | exec /usr/bin/node: exec format error`

It works when building with `build: .`, but not with any images.
Looking at the [docker hub tags](https://hub.docker.com/r/mauriceo/viewtube/tags), all of the dev images have the `linux/amd64` architecture, and manually specifying the `mauriceo/viewtube:dev-linux-arm64` image has the same result as `mauriceo/viewtube:dev`

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3"

services:
  viewtube:
    build: . # works
    container_name: viewtube
    restart: unless-stopped
    #image: mauriceo/viewtube:dev # does not work
    #image: mauriceo/viewtube:dev-linux-arm64 # does not work
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - VIEWTUBE_URL=http://localhost:8066
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_DATA_DIRECTORY=/data
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

networks:
  viewtube:
```

</details>

_Originally posted by @Myned in https://github.com/ViewTube/viewtube-vue/issues/979#issuecomment-1067445351_
