### ISSUE TITLE
search term empty

### ISSUE THREAD

**Issue by darkknight7777777** [mauriceoegerli/viewtube-vue#1446]
### Describe the Bug
fresh docker install, all containers show ready for connection. navigate to URL and attempt a search and see error:  

Search term is empty

Search term can't be empty

### Steps to Reproduce the Bug

1. Go to '...' homepage
2. type anything in search
3. . See the error ' upper right corner

### Expected Behaviour

search results

### Screenshot/Screen recording

![image](https://user-images.githubusercontent.com/87158641/174498574-ce6cd399-6478-4ef8-bc65-d9b3934cdab0.png)

### Device Info 

- Device: [e.g. iPhone6] laptop
- OS: [e.g. iOS8.1] windows 11
- Browser: [e.g. Firefox, Safari] occurs in all browsers (ff, chrome)
- Version: [e.g. 22] 101

### Additional Context

ETA: no errors shown on any of the containers.

using below compose 
```
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:0.9
    deploy:
      resources:
       limits:
#        cpus: '.25'
        memory: 350M

    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/config/viewtube/data:/data
    environment:
      - VIEWTUBE_URL=http://192.168.0.250:8066
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_REDIS_PORT=6379
#      - VIEWTUBE_REDIS_PASSWORD=empty
      - VIEWTUBE_DATA_DIRECTORY=/data
      - VIEWTUBE_CLUSTERED=false
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_DATABASE_PORT=27017
#      - VIEWTUBE_DATABASE_USER=viewtube
#      - VIEWTUBE_DATABASE_PASSWORD=empty
      - VIEWTUBE_ALLOWED_DOMAIN=http://192.168.0.*
      - VIEWTUBE_YOUTUBE_COOKIE=empty
      - VIEWTUBE_YOUTUBE_IDENTIFIER=empty
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
#    environment:
#          - DATABASE_USER=viewtube
#          - VIEWTUBE_DATABASE_PASSWORD=empty
    volumes:
      - /etc/config/viewtube/data/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - /etc/config/viewtube/data/redis:/data

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    restart: unless-stopped

networks:
  viewtube:

```
