### ISSUE TITLE
500 uri malformed on every page

### ISSUE THREAD

**Issue by Savanta** [mauriceoegerli/viewtube-vue#1894]
### Describe the Bug

500 uri malformed on every page
Only /api works

### Expected Behaviour

Working webpage

### Device Info

- Device: Docker
- OS: Docker
- Browser: Firefox/Vivaldi
- Version: latest stable

### Docker compose

```
version: '3'

services:
  viewtube:
    container_name: ViewTube
    restart: always
    # Or use mauriceo/viewtube:dev for the development version
    image: mauriceo/viewtube:latest
    # ViewTube will not start until the database and redis are ready
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    # Make sure all services are in the same network
    networks:
      - InternalNPM
    volumes:
      # This will map ViewTube's data directory to the local folder ./data/viewtube/
      - /media/Dane/.docker/viewtube/data:/data
    environment:
      - VIEWTUBE_URL=cloudtube.fluffstuff.pl

      - VIEWTUBE_SECURE=true
      - VIEWTUBE_DATA_DIRECTORY=/data
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis

  viewtube-mongodb:
    container_name: viewtube-mongodb
    restart: always
    image: mongo:5
    networks:
      - InternalNPM
    volumes:
      - /media/Dane/.docker/viewtube/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    restart: always
    image: redis:7
    networks:
      - InternalNPM
    volumes:
      - /media/Dane/.docker/viewtube/redis:/data

networks:
  InternalNPM:
      external: true
```

### Console output

```
[nuxt] [request error] [unhandled] [500] URI malformed
  at decodeURIComponent (<anonymous>)  
  at desanitize (./client/.output/server/chunks/app/server.mjs:1347:29)  
  at ./client/.output/server/chunks/app/server.mjs:1353:31  
  at Array.reduce (<anonymous>)  
  at parseCookieString (./client/.output/server/chunks/app/server.mjs:1350:139)  
  at ./client/.output/server/chunks/app/server.mjs:1585:19  
  at fn (./client/.output/server/chunks/app/server.mjs:138:27)  
  at Object.callAsync (./client/.output/server/node_modules/unctx/dist/index.mjs:49:19)  
  at callWithNuxt (./client/.output/server/chunks/app/server.mjs:140:23)  
  at applyPlugin (./client/.output/server/chunks/app/server.mjs:109:39)
```
