### ISSUE TITLE
Unable to select video qualities higher than 1280x720

### ISSUE THREAD

**Issue by JoshuaVandaele** [mauriceoegerli/viewtube-vue#2586]
I've just started hosting ViewTube through Docker, and while watching a video I cannot select a quality higher than 1280x720, even though the videos are available in 1920x1080 or even 4K on youtube.com
![image](https://github.com/ViewTube/viewtube/assets/24195176/edeb4327-627c-4f4e-aa05-c2c74599cd41)
Clicking the `1920x1080` button doesn't do anything at all.

If it helps, I have deployed ViewTube on a Raspberry pi 4 with this docker-compose:
```yml
version: '3'

networks:
  viewtube-local:
  networks_reverse_proxy:
    external: true

services:
  viewtube:
    image: mauriceo/viewtube:latest
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    networks:
      - networks_reverse_proxy
      - viewtube-local
    container_name: viewtube
    environment:
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
    volumes:
      - ./config-viewtube:/data
    restart: unless-stopped

  viewtube-mongodb:
    image: mongo:4.4.18
    networks:
      - viewtube-local
    volumes:
      - ./config-db:/data
    restart: unless-stopped

  viewtube-redis:
    image: redis
    networks:
      - viewtube-local
    volumes:
      - ./config-redis:/data
    restart: unless-stopped
```
