### ISSUE TITLE
Bug with Proxy

### ISSUE THREAD

**Issue by maaaaz** [mauriceoegerli/viewtube-vue#3001]
Hello there,

With this docker-compose file:
```
services:
  warp:
    image:  monius/docker-warp-socks:v3
    restart: unless-stopped
    container_name: warp

  viewtube:
    #build: .
    image: mauriceo/viewtube:latest
    ports:
      - 8066:8066
    volumes:
      - ./data:/data
    depends_on:
      - viewtube-db
      - viewtube-redis
    environment:
      VIEWTUBE_DATABASE_HOST: viewtube-db
      VIEWTUBE_REDIS_HOST: viewtube-redis
      VIEWTUBE_ADMIN_USER: admin
      VIEWTUBE_PROXY_URL: http://warp:9091

  viewtube-db:
    image: mongo
    ports:
      - 27018:27017

  viewtube-redis:
    image: redis
```

 I encounter the following bug that prevent any search and playback:

```
{
  "context": "ExceptionsHandler",
  "level": "error",
  "message": "Cannot read properties of undefined (reading 'match')",
  "stack": [
    "TypeError: Cannot read properties of undefined (reading 'match')\n    at parseAccessibilityDuration (/home/app/server/dist/mapper/utils/accessibility-duration.js:12:53)\n    at extractSearchShort (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:104:76)\n    at /home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:93:41\n    at Proxy.map (<anonymous>)\n    at extractSearchShortsShelf (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:93:29)\n    at /home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:28:24\n    at Proxy.map (<anonymous>)\n    at extractSearchResults (/home/app/server/dist/mapper/converter/search/vt-search-result.extractors.js:19:27)\n    at toVTSearchResultDto (/home/app/server/dist/mapper/converter/search/vt-search-result.converter.js:14:69)\n    at SearchService.getSearch (/home/app/server/dist/core/search/search.service.js:60:65)"
  ],
  "timestamp": "2025-01-09T20:58:14.006Z"
}
```

I suspect it is linked with the `VIEWTUBE_PROXY_URL` option.

Can you help ?

Cheers!
