### ISSUE TITLE
ECONREFUSED with provided Docker conf

### ISSUE THREAD

**Issue by ghost** [mauriceoegerli/viewtube-vue#920]
Hi,

I read the documentation and when running docker-compose up -d I get in the logs:
`[
ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
`

This is my docker-compose.yml file:
```
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:latest
    depends_on:
      - viewtube-mongodb
    networks:
      - viewtube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/me/viewtube/data:/data
    environment:
      - VIEWTUBE_JWT_SECRET=******
      - VIEWTUBE_CURRENT_DOMAIN=something.net
      - VIEWTUBE_DATA_DIRECTORY=/data
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - /home/me/viewtube/db:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    networks:
      - viewtube
    restart: unless-stopped
    volumes:
      - /home/me/viewtube/redis:/data

networks:
  viewtube:

```

I then reverse proxy with localhost:8066 with Nginx. I tried the project on the hosted instance and it's awesome.

How can I solve this? Thank you.
