### ISSUE TITLE
ERROR  Popular page refresh failed

### ISSUE THREAD

**Issue by FuzzyMistborn** [mauriceoegerli/viewtube-vue#968]
### Describe the Bug

I'd love to get this running, and at times I've gotten so far as the homepage (though no images).  Currently I'm running into the below error about invidious issues, though I'm not sure that's my main issue.

### Steps to Reproduce the Bug

Here's my docker-compose file.  The keys are just for testing.

```
version: "3"

services:
  viewtube:
    container_name: viewtube
    restart: unless-stopped
    image: mauriceo/viewtube:latest
    depends_on:
      - viewtube-mongodb
      - viewtube-redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/fuzzy/docker/viewtube/data:/data
    environment:
      - VIEWTUBE_API_URL=http://192.168.50.13:8066/api/
      - VIEWTUBE_CURRENT_DOMAIN=http://192.168.50.13:8066
      - VIEWTUBE_DATABASE_HOST=viewtube-mongodb
      - VIEWTUBE_REDIS_HOST=viewtube-redis
      - VIEWTUBE_JWT_SECRET=secretscret
      - VIEWTUBE_JWT_EXPIRATION_TIME=43200
      - VIEWTUBE_DATA_DIRECTORY=/data
      - VIEWTUBE_PUBLIC_VAPID=BFz-O58uOI24EZhkWifnWwehgdMFoOBu20RLzq-JTaB5PqmdoajmqUwJHEZP671WhvrCl1NN6kvlCBaeYYaEgio
      - VIEWTUBE_PRIVATE_VAPID=a1hBPSWMYvt7dDPQlQoq44gEeXa9wg5KFkxtuF4Dp-Q
    ports:
      - 8066:8066

  viewtube-mongodb:
    container_name: viewtube-mongodb
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - /home/fuzzy/docker/viewtube/mongo:/data/db

  viewtube-redis:
    container_name: viewtube-redis
    image: redis:6
    restart: unless-stopped
    volumes:
      - /home/fuzzy/docker/viewtube/redis:/data
```

### Expected Behaviour

Working app!

### Screenshot/Screen recording

Docker logs:

```
viewtube            | --- Environment variables ---
viewtube            | 
viewtube            | ~ Used default value for the following environment variables
viewtube            | PORT:                           8066
viewtube            | VIEWTUBE_DATABASE_PORT:         27017
viewtube            | VIEWTUBE_DATABASE_USER:         empty
viewtube            | VIEWTUBE_DATABASE_PASSWORD:     empty
viewtube            | VIEWTUBE_REDIS_PORT:            6379
viewtube            | VIEWTUBE_REDIS_PASSWORD:        empty
viewtube            | VIEWTUBE_ALLOWED_DOMAIN:        /^viewtube\.io|\.viewtube\.io$/
viewtube            | 
viewtube            | ✓ Found values for the following environment variables
viewtube            | VIEWTUBE_JWT_SECRET:            *****
viewtube            | VIEWTUBE_PUBLIC_VAPID:          BFz-O58uOI24EZhkWifnWwehgdMFoOBu20RLzq-JTaB5PqmdoajmqUwJHEZP671WhvrCl1NN6kvlCBaeYYaEgio
viewtube            | VIEWTUBE_PRIVATE_VAPID:         *****
viewtube            | VIEWTUBE_CURRENT_DOMAIN:        http://192.168.50.13:8066
viewtube            | VIEWTUBE_API_URL:               http://192.168.50.13:8066/api/
viewtube            | VIEWTUBE_DATABASE_HOST:         viewtube-mongodb
viewtube            | VIEWTUBE_REDIS_HOST:            viewtube-redis
viewtube            | VIEWTUBE_JWT_EXPIRATION_TIME:   43200
viewtube            | VIEWTUBE_DATA_DIRECTORY:        /data
viewtube            | ℹ Primary node started: pid 1
viewtube            | ℹ Worker node started: pid 15
viewtube            | ℹ Worker node started: pid 21
viewtube            | ℹ Worker node started: pid 80
viewtube            | ℹ Worker node started: pid 22
viewtube            | ℹ Worker node started: pid 74
viewtube            | ℹ Worker node started: pid 48
viewtube            | ℹ Worker node started: pid 59
viewtube            | ℹ Worker node started: pid 64
viewtube            | ℹ Worker node started: pid 34
viewtube            | ℹ Worker node started: pid 51
viewtube            | ℹ Worker node started: pid 41
viewtube            | ℹ Worker node started: pid 72
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ℹ Modern bundles are detected. Modern mode (server) is enabled now.
viewtube            | ready Server listening on http://localhost:8066
viewtube            | ℹ Refreshing popular page
viewtube            | 
viewtube            |  ERROR  Popular page refresh failed. URL: https://invidious.snopyta.org/api/v1/popular?fields=type,title,videoId,videoThumbnails,lengthSeconds,viewCount,author,authorId,publishedText
viewtube            | 
viewtube            | 
viewtube            |  ERROR  request to https://invidious.snopyta.org/api/v1/popular?fields=type,title,videoId,videoThumbnails,lengthSeconds,viewCount,author,authorId,publishedText failed, reason: getaddrinfo EAI_AGAIN invidious.snopyta.org
viewtube            | 
viewtube            |   at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1461:11)
viewtube            |   at ClientRequest.emit (node:events:394:28)
viewtube            |   at TLSSocket.socketErrorListener (node:_http_client:447:9)
viewtube            |   at TLSSocket.emit (node:events:394:28)
viewtube            |   at emitErrorNT (node:internal/streams/destroy:157:8)
viewtube            |   at emitErrorCloseNT (node:internal/streams/destroy:122:3)
viewtube            |   at processTicksAndRejections (node:internal/process/task_queues:83:21)
viewtube            | 
```

### Device Info 

- Device: Linux desktop
- OS: Arch
- Browser: Firefox
- Version: 92

### Additional Context

Not sure if related to https://github.com/ViewTube/viewtube-vue/issues/931 or https://github.com/ViewTube/viewtube-vue/issues/923
